/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sudhirsh' at '8/1/16 12:32 PM' with Gradle 2.4
 *
 * @author sudhirsh, @date 8/1/16 12:32 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
